//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhTin
    {
        public string TenFileAnh { get; set; }
        public string ViTri { get; set; }
        public string MaTin { get; set; }
    
        public virtual TinTuc TinTuc { get; set; }
    }
}
