//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIADIEM_TOUR
    {
        public string MaDD { get; set; }
        public string MaTour { get; set; }
        public string TenFileAnh { get; set; }
        public string ViTri { get; set; }
    
        public virtual Tour Tour { get; set; }
        public virtual DiemThamQuan DiemThamQuan { get; set; }
    }
}
